export interface AboutSlide {
  id: number;
  mainImageUrl: string;
  sideImageUrl: string;
}

export const ABOUT_SLIDES: AboutSlide[] = [
  {
    id: 1,
    mainImageUrl: "/image/About/Carousel/Arceus.png",
    sideImageUrl: "/image/About/Carousel/Charizard.png",
  },
  {
    id: 2,
    mainImageUrl: "/image/About/Carousel/Charizard.png",
    sideImageUrl: "/image/About/Carousel/Dragonite.png",
  },
  {
    id: 3,
    mainImageUrl: "/image/About/Carousel/Dragonite.png",
    sideImageUrl: "/image/About/Carousel/Lugia.png",
  },
  {
    id: 4,
    mainImageUrl: "/image/About/Carousel/Lugia.png",
    sideImageUrl: "/image/About/Carousel/Mew.png",
  },
  {
    id: 5,
    mainImageUrl: "/image/About/Carousel/Mew.png",
    sideImageUrl: "/image/About/Carousel/Pikachu.png",
  },
  {
    id: 6,
    mainImageUrl: "/image/About/Carousel/Pikachu.png",
    sideImageUrl: "/image/About/Carousel/Arceus.png",
  },
];

export interface CommitteeMember {
  id: number;
  name: string;
  role: string;
  photoUrl?: string;
  description?: string;
  member?: string[];
  position?: string[];
}

export interface CommitteeData {
  [key: string]: CommitteeMember[];
}

export const COMMITTEE_MEMBERS: CommitteeData = {
  PM: [
    {
      id: 1,
      name: "Nabila Shafa Sabrina, S.Sos",
      role: "Project Manager",
      photoUrl: "",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
  ],
  DPM: [
    {
      id: 2,
      name: "Harini Setyowati",
      role: "Deputy Manager for Finance & Secretarial Affairs",
      photoUrl: "",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      id: 3,
      name: "Nazwa Priyandini Cahyani Putri",
      role: "Deputy Event Manager",
      photoUrl: "",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      id: 4,
      name: "Andhika Pratama",
      role: "Deputy General Manager",
      photoUrl: "",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
  ],
  APM: [
    {
      id: 6,
      name: "Muhammad Akmal Baskoro",
      role: "APM Finance Dept",
      photoUrl: "",
      description:
        "The Finance Department is responsible for managing all financial aspects of an event or organization. This includes budgeting, tracking expenses, handling transactions, and ensuring financial transparency.",
      member: [
        "Harini Setyowati",
        "Muhammad Akmal Baskoro",
        "Syafa Aisha Putri",
        "Ahmad Zaky",
        "Aliya Putri",
        "Bunga Adelia",
        "Bunga Citra",
        "Dhimas Setyo Nugorho",
        "Shaula Chaerunnisa",
        "Dhenis Auliya Putri",
        "Rohma Zeva Aurelia Taufani",
      ],
      position: [
        "Assistent Project Manager",
        "Supervisor",
        "Cash Bookkeping",
        "Cash Bookkeping",
        "Field Treasurer & Administration",
        "Field Treasurer & Administration",
        "Field Treasurer & Administration",
        "Field Treasurer & Administration",
        "Field Treasurer & Administration",
        "Receipt and Note",
        "Receipt and Note",
      ],
    },
    {
      id: 7,
      name: "Wafa Ma'alim Fithoriq",
      role: "APM Secretarial Affairs Dept",
      photoUrl: "",
      description:
        "The Secretarial Affairs Department ensures smooth administrative operations, maintaining clear communication and documentation throughout the event planning and execution process.",
      member: [
        "Dwi Luvita Sari",
        "Shefiana Dhifta Yudha Octavia",
        "Syafira Ramadanty",
        "Nurul Rahmawati",
        "Chusnul nur Rahmahdhianti",
        "Zahrah Nura Eryunanza",
        "Zahwa Nabila Shaqi",
        "Khairunisa Salsabila Putri",
        "Suci Novia Triani",
        "Sabha Zidna Annabila",
      ],
      position: [
        "Assistent Project Manager",
        "Supervisor",
        "Finance Officer",
        "Correspondence Administration",
        "Correspondence Administration",
        "Correspondence Administration",
        "General Administration",
        "General Administration",
        "Event Admininstration",
        "Event Admininstration",
      ],
    },
    {
      id: 8,
      name: "Leila Alysia Syafiiqoh",
      role: "APM Debate Dept",
      photoUrl: "",
      description:
        "The Debate Department is responsible for organizing, managing, and overseeing debate-related activities and events.",
      member: [
        "Leila Alysia Syafiiqoh",
        "Asya Khairunnisa",
        "Muhammad Kahfi Rasyad",
        "Alda Rizka Nurhaliza",
        "Putri Rahmi Lestari",
        "Mourennisa Aulia",
        "Nadya Dwi Meidiana",
        "Khayla Namanda Putri",
        "Khairizza Amaya Shaina Kustiwa",
        "Akmal Farid",
        "Aulia Salma Fahira",
        "Novia Fitri Ramadhani",
        "Sawalia Putri Fadila",
        "Siti Fasya Nur Fadhilah",
        "Febri Sadewi Pujanti",
        "Jamine Amalia",
        "Diva Nurania Keyla Firdaus",
        "Nazwa Anindita Putri",
        "Muhammad Arya Kusuma",
        "Tania Cesilia Putri",
        "Muhammad Zendi Alfarizi",
        "Chaesya Firmanda Firdaus",
        "Almelia Restika",
        "Sandrina Maharini",
      ],
      position: [
        "Assistent Project Manager",
        "Supervisor",
        "Coordinator of EDC",
        "Coordinator of EDC",
        "Finance Officer",
        "PIC of Administration Division",
        "Administration Division",
        "Administration Division",
        "PIC of Event Division",
        "Event Division",
        "Event Division",
        "Event Division",
        "Event Division",
        "Event Division",
        "Event Division",
        "PIC of CAP Division",
        "CAP KDBI",
        "CAP EDC",
        "Tabulator KDBI",
        "Tabulator EDC",
        "Registration EDC",
        "Registration KDBI",
        "Ethics Code KDBI",
        "Ethics Code KDBI",
      ],
    },
    {
      id: 9,
      name: "Chairunnisa Salsabila",
      role: "APM Scientific Paper Competition Dept",
      photoUrl: "",
      description:
        "The Scientific Paper Competition Department is responsible for organizing and managing events focused on academic writing and research presentation.",
      member: [
        "Charunnisa Salsabila",
        "Nur Aisyah",
        "Hanifa Putri Oktaviani",
        "Muhammad Hafids",
        "Muhammad Azriel Alghifari",
        "Alvintia Asri Mariskandari",
        "Farhan Rasendrya Putra Isnanto",
        "Faras Aurora Dwi Nuary",
        "Maulana Ishak Faujan",
        "Nazwa Azdania",
        "Selfia Ningrum",
        "Arya Adi Ramadansyah",
        "Kesya Anggun Apriliana",
        "Reinata Natalia Embu",
        "Syiifa Khairani",
      ],
      position: [
        "Assistent Project Manager",
        "Administration & Finance Officer",
        "Administration & Finance Officer",
        "Coordinator",
        "Supervisor",
        "Ethics Code",
        "Tabulator",
        "CAP",
        "CAP",
        "Registration",
        "Registration",
        "Event",
        "Event",
        "Event",
        "Event",
      ],
    },
    {
      id: 10,
      name: "Eky Wijayanto",
      role: "APM Digital Content Competition Dept",
      photoUrl: "",
      description:
        "The Short Movie Competition Department is in charge of organizing and managing all aspects of the short movie competition.",
      member: [
        "Eky Wijayanto",
        "Firda Chaerunnisa",
        "Malika Ma'asya Putri Hermalia",
        "Mohammad Nabil Malik Futonik",
        "Akelens Pangestu",
        "Anisa Nada Noviriansyah",
        "Arrum Kulsuma Wardhani",
        "Arrum Tiara Salma",
        "Auryna Mahsa Syahrani",
        "Fazhri Septian Ardiansyah",
        "Fiesda Sekar Prastica",
        "Habibi Zamzami",
        "Maheswari Nabilah Fasya",
        "Muhammad Daffa",
        "Riani Nurfadillah",
        "Siti Nurlaila",
        "Sonya Nayla Azzahra",
        "Yohana Sonya Budiman",
        "Desya Aulia Putri",
        "Fatimah Aulia Rahma",
        "Nur Varissa Camelia",
        "Fatma Indriyani",
      ],
      position: [
        "Assistent Project Manager",
        "Supervisor",
        "Coordinator Short Video Compettion",
        "Coordinator Inforgraphic Competition",
        "Division of Event",
        "Division of Registration",
        "Division of Event",
        "Division of Administration",
        "Division of Event",
        "Division of Ethics Code",
        "Tabulator",
        "Division of CAP",
        "Division of Event",
        "Division of Registration",
        "Division of Event",
        "Division of Administration",
        "Division of CAP",
        "Division of Registration",
        "Finance Officer",
        "Division of Ethics Code",
        "Division of Tabulator",
        "Division of Event",
        "Division of CAP",
      ],
    },
    {
      id: 11,
      name: "Vanez Meida Olivia Putri",
      role: "APM Entertainment Dept",
      photoUrl: "",
      description:
        "The Entertainment Department is responsible for organizing and managing all entertainment-related activities for events.",
      member: [
        "Vanez Meida Olivia Putri",
        "Amanda Candra Prastika",
        "Aurellya Zahwa Maulina",
        "Az-Zahra Syafira",
        "Glory Maranatha Christiantoro",
        "Helwa Alby Maliha",
        "Jihan An'umillah Adzhani",
        "Kanya Alyna",
        "Nurul Cahya",
        "Taufik Kurahaman",
      ],
      position: [
        "Assistent Project Manager",
        "Supervisi",
        "Performance",
        "Mc and Moderator",
        "Mc and Moderator",
        "Performance",
        "Administration",
        "Performance",
        "Finance Officer",
        "Background Visual Effect",
      ],
    },
    {
      id: 12,
      name: "Muhammad Bisyr",
      role: "APM Advertising Dept",
      photoUrl: "",
      description:
        "The Advertising Department is tasked with creating and executing promotional strategies to maximize event visibility and engagement.",
      member: [
        "Muhammad Bisyr",
        "Sahfina Winata",
        "Mayesha Azzahra",
        "Nayla Rahma Putri",
        "Aiska Ramadya",
        "Rafif Abyan Hidayat",
        "Tisya Salsabrina",
        "Restu Bumi Anggraini",
        "Viola Febrianti",
        "Muhammad Delvyan Ramdhan Pratama",
        "Kayla Melinda Nggule",
        "Siti Marsya Aulia Saifullah",
        "Nayla Ayu Shahriza",
        "Azzahra Dara Febrianti",
        "Audina Alamanda Husnul Chotimah",
        "Nadia Ramadhani",
        "Najwa Khailillah Putri",
        "Yogi Finanda",
        "Jonathan Sandy Setiadi",
        "Hanifah Azzahra",
        "Nabiilah Septiana",
      ],
      position: [
        "Assistent Project Manager",
        "Supervisor",
        "Secretary & Finance Officer",
        "Division of Pers",
        "Division of Pers",
        "Division of Pers",
        "Division of Content Planner",
        "Division of Content Planner",
        "Division of Creator",
        "Division of Creator",
        "Division of Creator",
        "Division of Creator",
        "Division of Creator",
        "Division of Design",
        "Division of Design",
        "Division of Design",
        "Division of Design",
        "Division of Design",
        "Division of Documentary",
        "Division of Documentary",
        "Division of Documentary",
      ],
    },
    {
      id: 13,
      name: "Kyla Nazwara Sofyan",
      role: "APM Partnership Dept",
      photoUrl: "",
      description:
        "The Partnership Department focuses on building and managing relationships with external organizations, partners, and sponsors.",
      member: [
        "Kyla Nazwara Sofyan",
        "Leysa Regita Parhusip",
        "Triandi Muhammad Hafiz",
        "Citra Safara",
        "Rivan Wahyu Septian",
        "Salsabila Safitri",
        "Hisyam Farindra",
        "Najwa Chaela Khosiatillah",
        "Muhammad Fakhruddien",
        "Ahmad Kahirul Ilham",
        "Komang Ratih Melani Putri",
        "Afira Tria Sahara",
        "Az Zahra Nabila Pratiwi",
        "Ahmad Yazid Sholeh",
        "Ihda Annisa",
        "Fathya Azahra",
        "Rafli Faalih Erianto",
      ],
      position: [
        "Assistent Project Manager",
        "Supervision",
        "Secretaris",
        "Finance Officer",
        "Delegation Donator",
        "Delegation Sponsor",
        "Delegation Sponsor",
        "Delegation Sponsor",
        "Bazaar",
        "Bazaar",
        "Bazaar",
        "Bazaar",
        "Bazaar",
        "Media Partner",
        "Media Partner",
        "Marketing & Brand",
        "Marketing & Brand",
      ],
    },
    {
      id: 14,
      name: "Nasya Rizka Saputri",
      role: "APM Public Relation Dept",
      photoUrl: "",
      description:
        "The Public Relation (PR) Department is responsible for managing communication between the event organizers and the public, participants, sponsors, partners and stakeholders.",
      member: [
        "Nasya Rizka Saputri",
        "Nazhif Alhuwaidie",
        "Cahyani Yulia Rahma",
        "Annisa Salsabilatul Mashumah",
        "Syifa Aulia Fairuza",
        "Rangga Ramdhana",
        "Karini Putri Surya",
        "Jahra Atiar Husaeni",
        "Kasih Eigift Sinaga",
        "Hemalia Putri",
        "Muhammad Zaid Zidan",
        "Marsaa Fauziyyah",
        "Malik Hardiansyah",
      ],
      position: [
        "Assistent Project Manager",
        "Supervisor",
        "Secretary & Finance Officer",
        "Event Division of Debtate Competition (KDBI)",
        "Event Division of Debtate Competition (KDBI)",
        "Event Division of Debtate Competition (EDC)",
        "Event Division of Debtate Competition (EDC)",
        "Event Division of Scientific Paper Competition (SPC)",
        "Event Division of Scientific Paper Competition (SPC)",
        "Event Division of Digital COntent Competition (DCC)",
        "Event Division of Digital COntent Competition (DCC)",
        "Civitas",
        "Field Coordinator",
      ],
    },
    {
      id: 15,
      name: "Dimas",
      role: "APM IT Dept",
      photoUrl: "",
      description:
        "The Information Technology (IT) Department is responsible for designing, developing, and maintaining the digital platforms for the event, including unasfest.com and caturnawa.unasfest.com.",
      member: [
        "Dimas",
        "Najwa Aura Hastin",
        " Alya",
        "Galang Rispai",
        "Muhammad Zidan",
        "Raden Whisnu Arya Nugraha",
        "Nur Arohman",
        "Muhammad Akbar Hadi Pratama",
        "Ilham Ramadhan",
      ],
      position: [
        "Assistent Project Manager",
        "Techlead",
        "Secretarial Affairs & Finance Officer",
        "UI/UX Design",
        "UI/UX Design",
        "Front-end Developer",
        "Front-end Developer",
        "Back-end Developer",
        "Back-end Developer",
      ],
    },
    {
      id: 16,
      name: "Najmia",
      role: "APM Facility and Infrastructure Dept",
      photoUrl: "",
      description:
        "The Infrastructure Department is responsible for planning, organizing, and maintaining the physical resources required for events.",
      member: [
        "Andhika Pratama",
        "Maizahra Cahyani",
        "Muhammad Hammam Gifary",
        "Linda Isnaeni",
        "Afifah Aulia Paramitha Manurung",
        "Alya Giska Alivia",
        "Angga Wijaya",
        "Anggita Intan Anggaluh",
        "Aryo Bambang Nugroho",
        "Aulia Panggabean",
        "Davina Fadhillah Setiawan ",
        "Mohammad Fahreza Situmorang",
        "Muhammad Verdad",
        "Naufal Falah",
        "Yafi Arya Putra",
        "Zanuar Zaidan Zhahir",
        "Farhan Rizky Cahyadi",
        "Muhammad Ridho Jiyad",
        "Muhammad Mario Anthony Putra Defan",
        "Fatika Dwi Maiyeza",
      ],
      position: [
        "Assistent Project Manager",
        "Supervision",
        "Coordinator",
        "Secretary",
        "Division of Facility",
        "Inventory Officer",
        "Division of Facility",
        "Finance Officer",
        "Division of Infrastructure",
        "Division of Facility",
        "Secretary",
        "Division of Infrastructure",
        "Division of Infrastructure",
        "Division of Infrastructure",
        "Inventory Officer",
        "Division of Facility",
        "Division of Infrastructure",
        "Division of Infrastructure",
        "Division of Facility",
        "Division of Facility",
      ],
    },
    {
      id: 17,
      name: "Keysha Andani",
      role: "APM Food & Beverage Dept",
      photoUrl: "",
      description:
        "The Food and Beverage (F&B) Department is responsible for planning, organizing, and delivering meals, snacks, and beverages during events.",
      member: [
        "Keysha Andani",
        "Aprilia Candrawati",
        "Selviana Putri",
        "Nadilla Amanda Fernando",
        "Adni Gita Suryani",
        "Alya Rahmawati",
        "Ariesta Nur Halimah",
        "Chika Putri Sya'bani",
        "Diva Ayudhya Januar Rahman",
        "Dzikrina Zahra",
        "Langgeng Muhammad Yurham",
        "Muhammad Awallin Khalid",
        "Nurul Mayzidah",
        "Prajna Paramita",
        "Rico Aditya Aldafha",
        "Wahyu Zaaqi Fadila",
        "Muthia Amelia",
      ],
      position: [
        "Assistent Project Manager",
        "Secretary",
        "Supervision",
        "Committee",
        "Participants",
        "Committee",
        "Committee",
        "Logistics",
        "Logistics",
        "Finance Officer",
        "Participants",
        "Logistics",
        "VIP and Invitation",
        "VIP and Invitation",
        "Logistics",
        "VIP and Invitation",
        "Participants",
      ],
    },
    {
      id: 18,
      name: "Nayla Luthfia Hayati",
      role: "APM Health Dept",
      photoUrl: "",
      description:
        "The Health Department is tasked with ensuring the physical well-being and safety of all committee and participants during events.",
      member: [
        "Nayla Luthfia Hayati",
        "Ailsa Shafa Adriyani",
        "Anisa Anggraini",
        "Sakina Paradila Risci",
        "Abi Mohamad Landung",
        "Aisyah Nadin Putri Andiyani",
        "Bintang Dama Sutendi",
        "Dafa Annazi",
        "Gita Safitri",
        "Ramdhan Rasyid Zidan",
        "Salwa Salsabilla Fitri",
        "Suci Ramadhani",
      ],
      position: [
        "Assistent Project Manager",
        "Supervision",
        "Coordinator",
        "Secretaris and Finance Officer",
        "Controlling",
        "Controlling",
        "Controlling",
        "PostTeam",
        "PostTeam",
        "Controlling",
        "Controlling",
        "Clinic UNAS",
      ],
    },
    {
      id: 19,
      name: "Juandhika Irama",
      role: "APM Security Dept",
      photoUrl: "",
      description:
        "The Security Department is responsible for ensuring the safety and security of all participants, guests, and assets during events.",
      member: [
        "Juandhika Irama",
        "Muhammad Taufiqulhakim",
        "Tasya Sharadin Azzahra",
        "Muhammad Aufa Roiszul Hakim",
        "Ahmad Irfan Al Faqih",
        "Andjani Kinasih Cahyaningtyas",
        "Angger Subhan Nugroho",
        "Arya Wiratama",
        "Gabas Mohamed Daifalla Yogoub",
        "Kansah Novi Calia",
        "Muhammad Jufri Ramadhan",
        "Muhammad Rizky Dwi Saputro",
        "Putri Dini Sapitri",
        "Zahwa Alifa Rachman",
      ],
      position: [
        "Assistent Project Manager",
        "Supervision",
        "Secretary and Finance Officer",
        "Crowd Control & Preparation",
        "Patroly Team",
        "Patroly Team",
        "Patroly Team",
        "Crowd Control & Preparation",
        "Coordinator",
        "Crowd Control & Preparation",
        "Patroly Team",
        "Crowd Control & Preparation",
        "Crowd Control & Preparation",
        "Patroly Team",
      ],
    },
  ],
};

export const COMMITTEE_TABS: string[] = ["PM", "DPM", "APM"];
