import { CompetitionEvent } from "@/lib/types/Activities/Timeline";

export const EVENTS: CompetitionEvent[] = [
  {
    path: "/",
    timeline: [
      { month: "SEPTEMBER", day: "1-7", year: "2025", title: "Registration Competition - Early Bird" },
      { month: "SEPTEMBER", day: "8-19", year: "2025", title: "Registration Competition - Phase 1" },
      { month: "SEPTEMBER", day: "20-28", year: "2025", title: "Registration Competition - Phase 2" },
      { month: "OCTOBER", day: "2-4", year: "2025", title: "Administration SPC and DCC" },
      { month: "OCTOBER", day: "6", year: "2025", title: "Technical Meeting for Participants DCC" },
      { month: "OCTOBER", day: "7", year: "2025", title: "Annoucement Administration SPC and DCC" },
      { month: "OCTOBER", day: "9", year: "2025", title: "Technical Meeting for Participants Debate Competition" },
      { month: "OCTOBER", day: "8-21", year: "2025", title: "Collection of SPC and DCC Assignments and Assessment" },
      { month: "OCTOBER", day: "13-14", year: "2025", title: "Preliminary Round - Debate Competition" },
      { month: "OCTOBER", day: "15", year: "2025", title: "Semifinal Debate Competiton" },
      { month: "OCTOBER", day: "22", year: "2025", title: "Annoucement of Finalist SPC and DCC" },
      { month: "OCTOBER", day: "23-25", year: "2025", title: "PPT Collection of DCC" },
      { month: "OCTOBER", day: "27", year: "2025", title: "Final Round All Competition" },
      { month: "NOVEMBER", day: "6", year: "2025", title: "Awarding Ceremony UNAS FEST 2025" },
    ],
  },
  {
    path: "KDBI",
    timeline: [
      { month: "SEPTEMBER", day: "1-7", year: "2025", title: "Registration KDBI - Early Bird" },
      { month: "SEPTEMBER", day: "8-19", year: "2025", title: "Registration KDBI - Phase 1" },
      { month: "SEPTEMBER", day: "20-28", year: "2025", title: "Registration KDBI - Phase 2" },
      { month: "OCTOBER", day: "9", year: "2025", title: "Webinar and Participants Technical Meeting" },
      { month: "OCTOBER", day: "13", year: "2025", title: "Preliminary Round - Day 1" },
      { month: "OCTOBER", day: "14", year: "2025", title: "Preliminary Round - Day 2" },
      { month: "OCTOBER", day: "15", year: "2025", title: "Semifinal KDBI and EDC" },
      { month: "OCTOBER", day: "27", year: "2025", title: "Final Round" },
      { month: "NOVEMBER", day: "6", year: "2025", title: "Awarding Ceremony UNAS FEST 2025" },
    ],
  },
  {
    path: "EDC",
    timeline: [
      { month: "SEPTEMBER", day: "1-7", year: "2025", title: "Registration EDC - Early Bird" },
      { month: "SEPTEMBER", day: "8-19", year: "2025", title: "Registration EDC - Phase 1" },
      { month: "SEPTEMBER", day: "20-28", year: "2025", title: "Registration EDC - Phase 2" },
      { month: "OCTOBER", day: "9", year: "2025", title: "Webinar and Participants Technical Meeting" },
      { month: "OCTOBER", day: "13", year: "2025", title: "Preliminary Round - Day 1" },
      { month: "OCTOBER", day: "14", year: "2025", title: "Preliminary Round - Day 2" },
      { month: "OCTOBER", day: "15", year: "2025", title: "Semifinal Debate" },
      { month: "OCTOBER", day: "27", year: "2025", title: "Final Round" },
      { month: "NOVEMBER", day: "6", year: "2025", title: "Awarding Ceremony UNAS FEST 2025" },
    ],
  },
  {
    path: "SPC",
    timeline: [
      { month: "SEPTEMBER", day: "1-7", year: "2025", title: "Registration SPC - Early Bird" },
      { month: "SEPTEMBER", day: "8-19", year: "2025", title: "Registration SPC - Phase 1" },
      { month: "SEPTEMBER", day: "20-28", year: "2025", title: "Registration SPC - Phase 2" },
      { month: "OCTOBER", day: "2-4", year: "2025", title: "Administration Selection and Assessment of Outstanding Achievements of SPC Participants" },
      { month: "OCTOBER", day: "7", year: "2025", title: "Annoucement of Passing Administration Selection" },
      { month: "OCTOBER", day: "8-17", year: "2025", title: "Collection of SPC Script" },
      { month: "OCTOBER", day: "18-21", year: "2025", title: "Assessment of SPC Script by the Jury" },
      { month: "OCTOBER", day: "22", year: "2025", title: "Annoucement of 6 Finalists" },
      { month: "OCTOBER", day: "23", year: "2025", title: "Technical Meeting of Participants" },
      { month: "OCTOBER", day: "27", year: "2025", title: "Implementation of the Final Round" },
      { month: "NOVEMBER", day: "6", year: "2025", title: "Awarding Ceremony UNAS FEST 2025" },
    ],
  },
  {
    path: "Infographic",
    timeline: [
      { month: "SEPTEMBER", day: "1-7", year: "2025", title: "Registration Infographic - Early Bird" },
      { month: "SEPTEMBER", day: "8-19", year: "2025", title: "Registration Infographic - Phase 1" },
      { month: "SEPTEMBER", day: "20-28", year: "2025", title: "Registration Infographic - Phase 2" },
      { month: "OCTOBER", day: "2-4", year: "2025", title: "Ellimination of Participants by the Committee" },
      { month: "OCTOBER", day: "6", year: "2025", title: "Technical Meeting for Participants DCC" },
      { month: "OCTOBER", day: "7", year: "2025", title: "Annoucement" },
      { month: "OCTOBER", day: "8-17", year: "2025", title: "Submission of works" },
      { month: "OCTOBER", day: "18-21", year: "2025", title: "Assessment" },
      { month: "OCTOBER", day: "22", year: "2025", title: "Annoucement" },
      { month: "OCTOBER", day: "23-25", year: "2025", title: "PPT Collection" },
      { month: "OCTOBER", day: "27", year: "2025", title: "Final" },
      { month: "NOVEMBER", day: "6", year: "2025", title: "Awarding Ceremony UNAS FEST 2025" },
    ],
  },
  {
    path: "Short-Video",
    timeline: [
     { month: "SEPTEMBER", day: "1-7", year: "2025", title: "Registration Short Video - Early Bird" },
      { month: "SEPTEMBER", day: "8-19", year: "2025", title: "Registration Short Video - Phase 1" },
      { month: "SEPTEMBER", day: "20-28", year: "2025", title: "Registration Short Video - Phase 2" },
      { month: "OCTOBER", day: "2-4", year: "2025", title: "Ellimination of Participants by the Committee" },
      { month: "OCTOBER", day: "6", year: "2025", title: "Technical Meeting for Participants DCC" },
      { month: "OCTOBER", day: "7", year: "2025", title: "Annoucement" },
      { month: "OCTOBER", day: "8-17", year: "2025", title: "Submission of works" },
      { month: "OCTOBER", day: "18-21", year: "2025", title: "Assessment" },
      { month: "OCTOBER", day: "22", year: "2025", title: "Annoucement" },
      { month: "OCTOBER", day: "23-25", year: "2025", title: "PPT Collection" },
      { month: "OCTOBER", day: "27", year: "2025", title: "Final" },
      { month: "NOVEMBER", day: "6", year: "2025", title: "Awarding Ceremony UNAS FEST 2025" },
    ],
  },
];
